version: "3.3"
services:
  ckb:
    image: iobridge/ckb-dev:v0.100.0
    ports:
      - "8114:8114"
    networks:
      iobridgenet:
        ipv4_address: 10.5.0.11
        aliases:
          - ckb
  ckb-indexer:
    image: iobridge/ckb-indexer:v0.3.0
    ports:
      - "8116:8116"
    environment:
      - RUST_LOG=info
    command: ckb-indexer -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
    networks:
      iobridgenet:
        ipv4_address: 10.5.0.12
        aliases:
          - ckb-indexer
networks:
  iobridgenet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16